env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  comma-spacing: error
  comma-style: error
  curly:
    - error
    - multi-line
    - consistent
  dot-location:
    - error
    - property
  indent:
    - error
    - tab
  semi:
    - error
    - always
  no-var: error
  '@typescript-eslint/explicit-module-boundary-types': off
