env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - '@sapphire/eslint-config'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-console: off
  no-lonely-if: warn
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/no-non-null-assertion': off
