env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  brace-style:
    - warn
    - stroustrup
    - allowSingleLine: true
  comma-spacing: warn
  comma-style: warn
  curly:
    - warn
    - multi-line
    - consistent
  dot-location:
    - warn
    - property
  indent:
    - warn
    - tab
  semi:
    - warn
    - always
  no-console: off
  no-empty-function: warn
  no-lonely-if: warn
  no-var: warn
  no-trailing-spaces: error
  prefer-const: warn
  '@typescript-eslint/explicit-module-boundary-types': off
