version: '3.9'

services:
  spectera-bot:
    build:
      context: .
      target: development
    env_file: .env.production
    volumes:
      - ./:/opt/app
  postgres:
    container_name: postgres
    image: spectera-postgres:latest
    ports:
      - '5433:5432'
