version: '3.9'

services:
  spectera-bot:
    build:
      context: .
      target: development
    env_file: .env.production
    volumes:
      - ./:/opt/app
  postgres:
    container_name: postgres
    image: undiedgamer/postgres:0.5.0
    ports:
      - '6969:5432'
    networks:
      - spectera
networks:
  spectera:
