name: CI
on:
  push:
  pull_request:
jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      with:
        node-version: '16.x'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn prettier -c .