name: CI
on:
  push:
  pull_request:
jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn --immutable-cache
      - run: yarn build
      - run: yarn prettier -c .
